name: deenruv-local
services:
    deenruv-postgres:
        image: docker.io/postgis/postgis:16-3.4
        hostname: deenruv-postgres
        container_name: deenruv-postgres
        environment:
            POSTGRES_USER: deenruv
            POSTGRES_PASSWORD: deenruv
            POSTGRES_DB: deenruv
        ports:
            - 5432:5432
        expose:
            - 5432
    deenruv-redis:
        image: bitnami/redis:7.2
        hostname: deenruv-redis
        container_name: deenruv-redis
        environment:
            ALLOW_EMPTY_PASSWORD: yes
        ports:
            - 6379:6379
        expose:
            - 6379
    deenruv-minio:
        image: 'minio/minio:latest'
        hostname: deenruv-minio
        container_name: deenruv-minio
        ports:
            - 9000:9000
            - 9090:9090
        expose:
            - 9000
            - 9090
        environment:
            MINIO_ROOT_USER: 'root'
            MINIO_ROOT_PASSWORD: 'password'
        command: minio server /data/minio --console-address ":9090"
