blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://deenruv.com/docs
    about: Check the documentation for guides and API reference
  - name: Discussions
    url: https://github.com/aexol-studio/deenruv/discussions
    about: Ask questions and discuss ideas with the community
